version: "3.3"
services:

  redis:
    image: "redis:alpine"
    command: "redis-server --appendonly yes --port 6480"
    ports:
      - "6491:6480"
    volumes:
      - ./redis:/data
    restart: "always"

  redis-commander:
    depends_on:
      - "redis"
    image: "rediscommander/redis-commander:latest"
    restart: "always"
    environment:
      - "REDIS_HOSTS=local:redis:6480"
    ports:
      - "8191:8081"

  backend:
    ports:
      - "80:8000"
    volumes:
      - ./backend/app:/app
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: uvicorn --reload --host 0.0.0.0 app.main:app
    env_file:
      - .env
